language: erlang
otp_release:
  - R16B
  - R15B03
  - R15B02
  - R15B01
  - R14B04
before_script:
  - psql -f estatsdb/src/sql/bootstrap_database.sql -U postgres
  - psql -f estatsdb/src/sql/create_estatsdb_functions.sql -U postgres estatsdb
script: "make -C estatsdb test"
